# Generated by Django 4.2.28 on 2026-02-17 15:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome de exibição do restaurante', max_length=200, verbose_name='Nome do Restaurante')),
                ('subdominio', models.SlugField(help_text='Identificador único na URL (ex: pizzaria1)', max_length=100, unique=True, verbose_name='Subdomínio')),
                ('descricao', models.TextField(blank=True, help_text='Descrição curta do restaurante para exibição no cardápio', verbose_name='Descrição')),
                ('endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurantes/logos/', verbose_name='Logo')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=5.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Entrega (R$)')),
                ('pedido_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pedido Mínimo (R$)')),
                ('raio_entrega_km', models.DecimalField(decimal_places=1, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Raio de Entrega (km)')),
                ('taxa_imposto', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de imposto aplicado sobre o subtotal', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taxa de Imposto (%)')),
                ('horario_abertura', models.TimeField(default='08:00', verbose_name='Horário de Abertura')),
                ('horario_fechamento', models.TimeField(default='23:00', verbose_name='Horário de Fechamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
                'ordering': ['nome'],
            },
        ),
    ]
