# Generated by Django 4.2.28 on 2026-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0005_tamanhopizza'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='restaurante',
            index=models.Index(fields=['subdominio'], name='idx_restaurante_subdominio'),
        ),
        migrations.AddIndex(
            model_name='restaurante',
            index=models.Index(fields=['ativo'], name='idx_restaurante_ativo'),
        ),
        migrations.AddIndex(
            model_name='restaurante',
            index=models.Index(fields=['proprietario'], name='idx_restaurante_proprietario'),
        ),
    ]
