# Generated by Django 4.2.28 on 2026-04-11 01:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0006_restaurante_idx_restaurante_subdominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude do restaurante (ex: -23.5505). Necessária para zonas de entrega por raio.', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude do restaurante (ex: -46.6333). Necessária para zonas de entrega por raio.', null=True, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='ZonaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Zona Centro, Zona Bairros, Zona Rural', max_length=80, verbose_name='Nome da Zona')),
                ('raio_max_km', models.DecimalField(decimal_places=2, help_text='Distância máxima em km do restaurante para esta zona', max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Raio Máximo (km)')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taxa de Entrega (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor raio primeiro (será ordenado automaticamente)', verbose_name='Ordem')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_entrega', to='restaurantes.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Zona de Entrega',
                'verbose_name_plural': 'Zonas de Entrega',
                'ordering': ['raio_max_km'],
                'unique_together': {('restaurante', 'nome')},
            },
        ),
    ]
