# Generated by Django 4.2.28 on 2026-04-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0007_add_coords_and_zonaentrega'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='restaurante',
            name='idx_restaurante_subdominio',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='subdominio',
        ),
    ]
