# Generated by Django 4.2.28 on 2026-04-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0008_remove_restaurante_idx_restaurante_subdominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='subdominio',
            field=models.SlugField(default='', help_text='Identificador único na URL (ex: pizzaria1)', max_length=100, unique=True, verbose_name='Subdomínio'),
        ),
    ]
