# Generated by Django 4.2.28 on 2026-04-28 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantes', '0009_restore_subdominio_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
    ]
