# Generated by Django 4.2.28 on 2026-02-17 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('cliente_telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('endereco_entrega', models.TextField(blank=True, verbose_name='Endereço de Entrega')),
                ('tipo_entrega', models.CharField(choices=[('delivery', 'Delivery'), ('retirada', 'Retirada no Local')], default='delivery', max_length=10, verbose_name='Tipo de Entrega')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal (R$)')),
                ('taxa_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Taxa de Entrega (R$)')),
                ('imposto', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Imposto (R$)')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total (R$)')),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('preparo', 'Em Preparo'), ('entrega', 'Saiu para Entrega'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='recebido', max_length=10, verbose_name='Status')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurantes.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário (R$)')),
                ('observacao', models.CharField(blank=True, max_length=300, verbose_name='Observação do Item')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
