# Generated by Django 4.2.28 on 2026-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_itempedido_tamanho_sabores'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['restaurante', 'status'], name='idx_pedido_rest_status'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['restaurante', 'criado_em'], name='idx_pedido_rest_criado'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status', 'criado_em'], name='idx_pedido_status_criado'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['stripe_payment_intent_id'], name='idx_pedido_stripe'),
        ),
    ]
