# Generated by Django 4.2.28 on 2026-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_idx_pedido_rest_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['pedido'], name='idx_itempedido_pedido'),
        ),
        migrations.AddIndex(
            model_name='itempedido',
            index=models.Index(fields=['produto'], name='idx_itempedido_produto'),
        ),
    ]
