# Generated by Django 4.2.28 on 2026-02-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_fix_missing_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP INDEX IF EXISTS idx_pedido_gateway;
                ALTER TABLE pedidos_pedido DROP COLUMN IF EXISTS gateway_payment_id;
                ALTER TABLE pedidos_pedido DROP COLUMN IF EXISTS forma_pagamento;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]

