# Generated by Django 4.2.28 on 2026-03-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_cleanup_legacy_payment_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Pagamento'), ('recebido', 'Recebido'), ('preparo', 'Em Preparo'), ('entrega', 'Saiu para Entrega'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando', max_length=10, verbose_name='Status'),
        ),
    ]
