# Generated by Django 4.2.28 on 2026-04-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_rename_payment_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Pagamento'), ('aguardando_confirmacao', 'Aguardando Confirmação'), ('recebido', 'Recebido'), ('preparo', 'Em Preparo'), ('entrega', 'Saiu para Entrega'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando', max_length=25, verbose_name='Status'),
        ),
    ]
