# Generated by Django 4.2.28 on 2026-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_extend_status_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], default='dinheiro', max_length=10, verbose_name='Forma de Pagamento'),
        ),
    ]
