# Generated by Django 4.2.28 on 2026-04-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_add_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], default='pix', max_length=10, verbose_name='Forma de Pagamento'),
        ),
    ]
