# Generated by Django 4.2.28 on 2026-05-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0010_change_proprietario_to_fk'),
        ('pedidos', '0012_fix_historical_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando Pagamento'), ('aguardando_confirmacao', 'Aguardando Confirmação'), ('recebido', 'Recebido'), ('preparo', 'Em Preparo'), ('entrega', 'Saiu para Entrega'), ('pronto_retirada', 'Pronto para Retirada'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aguardando', max_length=25, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='Chave p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='Chave auth')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='pedidos.pedido', verbose_name='Pedido')),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='restaurantes.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
            },
        ),
    ]
