# Generated by Django 4.2.28 on 2026-02-18 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_categoria_adicional_sabor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Opcional. Se vazio, usa o adicional do tipo de sabor.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço (R$)'),
        ),
    ]
