# Generated by Django 4.2.28 on 2026-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_preco'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['restaurante', 'ativo', 'ordem'], name='idx_cat_rest_ativo_ord'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['restaurante', 'disponivel'], name='idx_prod_rest_disponivel'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['restaurante', 'categoria', 'disponivel'], name='idx_prod_rest_cat_disp'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['disponivel', '-destaque'], name='idx_prod_disp_destaque'),
        ),
    ]
