# Generated by Django 4.2.28 on 2026-02-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_categoria_idx_cat_rest_ativo_ord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='eh_pizza',
            field=models.BooleanField(
                default=True,
                help_text='Marque para categorias que usam lógica de pizza (tamanho + sabores).',
                verbose_name='Categoria de Pizza',
            ),
        ),
    ]

