# Generated by Django 4.2.28 on 2026-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['pedido'], name='idx_pagamento_pedido'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['status', 'criado_em'], name='idx_pagamento_status_criado'),
        ),
    ]
