# Generated by Django 4.2.28 on 2026-02-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_add_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE pagamentos_pagamento
                ADD COLUMN IF NOT EXISTS stripe_payment_intent_id varchar(255) NOT NULL DEFAULT '';

                ALTER TABLE pagamentos_pagamento
                DROP COLUMN IF EXISTS gateway_payment_id;

                ALTER TABLE pagamentos_pagamento
                DROP COLUMN IF EXISTS metodo_pagamento;

                ALTER TABLE pagamentos_pagamento
                DROP COLUMN IF EXISTS pix_qr_code;

                ALTER TABLE pagamentos_pagamento
                DROP COLUMN IF EXISTS pix_copia_cola;

                ALTER TABLE pagamentos_pagamento
                DROP COLUMN IF EXISTS expira_em;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]

