# Generated by Django 4.2.28 on 2026-03-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_align_pagamentos_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='gateway',
            field=models.CharField(choices=[('mp', 'Mercado Pago'), ('mock', 'Mock (Simulação)')], default='mock', max_length=10, verbose_name='Gateway'),
        ),
    ]
