# Generated by Django 4.2.28 on 2026-04-03 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0006_switch_to_mercadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf'])], verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='gateway',
            field=models.CharField(choices=[('mercadopago', 'Mercado Pago (descontinuado)'), ('mock', 'Mock (Simulação)'), ('pix_manual', 'PIX Manual')], default='mock', max_length=15, verbose_name='Gateway'),
        ),
    ]
