# Generated by Django 4.2.28 on 2026-04-10 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurantes', '0006_restaurante_idx_restaurante_subdominio_and_more'),
        ('pagamentos', '0007_add_pix_manual_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChavePix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('uuid', 'Chave Aleatoria')], max_length=16, verbose_name='Tipo')),
                ('valor', models.CharField(max_length=120, verbose_name='Valor')),
                ('valor_normalizado', models.CharField(blank=True, max_length=120, verbose_name='Valor Normalizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrao')),
                ('prioridade', models.PositiveIntegerField(default=100, verbose_name='Prioridade')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves_pix', to='restaurantes.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Chave PIX',
                'verbose_name_plural': 'Chaves PIX',
                'ordering': ['prioridade', 'id'],
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pix_chave_id_snapshot',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID da Chave PIX (Snapshot)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pix_chave_tipo_snapshot',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Tipo da Chave PIX (Snapshot)'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='pix_chave_valor_snapshot',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Valor da Chave PIX (Snapshot)'),
        ),
        migrations.CreateModel(
            name='ChavePixHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criacao'), ('edicao', 'Edicao'), ('ativacao', 'Ativacao'), ('desativacao', 'Desativacao'), ('padrao', 'Mudanca de padrao'), ('prioridade', 'Mudanca de prioridade')], max_length=20, verbose_name='Acao')),
                ('antes', models.JSONField(blank=True, null=True, verbose_name='Antes')),
                ('depois', models.JSONField(blank=True, null=True, verbose_name='Depois')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_chaves_pix', to=settings.AUTH_USER_MODEL, verbose_name='Ator')),
                ('chave_pix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pagamentos.chavepix', verbose_name='Chave PIX')),
            ],
            options={
                'verbose_name': 'Historico de Chave PIX',
                'verbose_name_plural': 'Historico de Chaves PIX',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='chavepix',
            index=models.Index(fields=['restaurante', 'ativo'], name='idx_chave_pix_rest_ativo'),
        ),
        migrations.AddIndex(
            model_name='chavepix',
            index=models.Index(fields=['restaurante', 'padrao', 'ativo'], name='idx_chave_pix_rest_padrao'),
        ),
        migrations.AddConstraint(
            model_name='chavepix',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True), ('padrao', True)), fields=('restaurante',), name='uq_chave_pix_padrao_ativa_por_restaurante'),
        ),
        migrations.AddConstraint(
            model_name='chavepix',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('restaurante', 'prioridade'), name='uq_chave_pix_prioridade_ativa_por_restaurante'),
        ),
    ]
