# Generated by Django 4.2.28 on 2026-02-17 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantes', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('veiculo', models.CharField(choices=[('moto', 'Moto'), ('bicicleta', 'Bicicleta'), ('carro', 'Carro'), ('a_pe', 'A Pé')], default='moto', max_length=10, verbose_name='Veículo')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregadores', to='restaurantes.restaurante', verbose_name='Restaurante')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entregador', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Entregador'), ('coletado', 'Coletado'), ('em_transito', 'Em Trânsito'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('saiu_em', models.DateTimeField(blank=True, null=True, verbose_name='Saiu em')),
                ('entregue_em', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='entregas.entregador', verbose_name='Entregador')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
