# Generated by Django 4.2.28 on 2026-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['status', 'criado_em'], name='idx_entrega_status_criado'),
        ),
        migrations.AddIndex(
            model_name='entrega',
            index=models.Index(fields=['entregador', 'status'], name='idx_entrega_entregador'),
        ),
        migrations.AddIndex(
            model_name='entregador',
            index=models.Index(fields=['restaurante', 'disponivel', 'ativo'], name='idx_entregador_disp'),
        ),
    ]
